id = "frank"  # https://collections.artsmia.org/art/1721/frank-chuck-close
name = "Frank by Chuck Close"
ascii_data = """
````..................................--------------------------------------------------------....--
````````````````````````````````````````````..`.................```.`.........````................--
``````````````````````````````````````````.................`....``````````````````````````.`...``.--
`````````````````````````````````````````..--::----::----........````````````````````````````````.--
```````````````````````````````````````..-.-::::////////:::---.......````````````````````````````.--
``````````````````````````````````.....--::///+/+oooooooooo+++/:--......`````````````````````````..-
``````````````````````````````....--::::/+++oooooooooossssoooo+o+//::-....```````````````````````..-
`````````````````````````...-:///+o+ooooossssssssoooooosssssssyss++o++/--.```````````````````````..-
``````````````````````...-::+oossssssyyyyyyyyyyyss+osossssosyssoosoo+oo+:-....````````````````````..
````````````````````.-:/+osoyyooossyyyhyssssyysoysosssyssysyyyssoossssss+:--...```````````````````..
``````````````````..:+osoooosssssyyyyhhhyyyhhhyyyhyyyyssssoyhyosoossoooss++/-...``````````````````..
`````````````````.:/oooossssysoosyyyyyyyhhyhhhhhhhhhdhsysyyhhyysooosssssosoo+-...`````````````````..
```````````````.-:+oss+sssoyhhssysyssyhhhhhhhyyyhhyhhdyysshdysssssosysysssso+:-..`````````````````..
`````````````.-:/ossyy+ssssoysoyyyyyyyyyyyhyyyhhysshddhyyssssohhhyssyyyssssoo+/-..````````````````..
````````````.-/oossyyhysyyyshyyhhhyyhhhhyyyyyyhhyyhhdddhhyssyhhhhyyyhsoossssooo/:-.```````````````..
````````````.:oyyyyyyhys+yyyhyyyyhhyhhhyyddhhhhhhhhhdhhhhyyyyyyhhyyyssssssssssoo+:-..`````````````..
```````````.-/ssyyyyhys+/ysyhhhdyyyyhddydddddddmmmddhyyyyysssyyhhddhyyhyysssysoso/-..`````````````..
`````````.-/ossssssyhys++syyyhhhhysydddddddmddddhhyyssso++++oossshdhyyhhsyyssssso/:-.`````````````..
`````````.:ossyysyyyhhyssssyyhhhhhhddmddddddddhhyssssso+///+++/++oyhyyyhhyyssyyso+//:-..``````````..
`````````-:+syyyyyyyhhhhysssyhdddddmddddddhhhhhysssssso/:::/o+:/++osyyyyyyhysyyyssooo/::-.````````..
```````.-:/+oyyyyyyydddddhhhhhhddddddddhhyysssssssssso+:--/+++++//oosyhhhhyyyysyyyyss+//:-.```````..
``````--:+++oyhhyyhhhdddddddddddddddddhysso+++/+ooooo/:-----:::---:+osyhhysossyyyyssooo//:..``````..
``````--::--/shhyyhhhhdddddddddddhhhyyssoo+++////////:-------------:+ssyhyoyyyssyyyyso+++/-.``````..
```````.:/-:+syysyhhhhhddhdddhhhhyyyyssssoooo++////::::://///:::::-::osyyhyhhyssyhyys+++++-..`````..
```````..:+ssyhhyyhhhhyhhdddhyyyhyyyyssssssyssoooo+/:/+oossssoooo+//:/syyhhhyyosyyso+++o++-..`````..
```````-:+oosyyyhyyddddddddddyyyyyyhhyyyhhyyhyyyyss+++oyyhyyyyyyyyyyyyhddhhhhhysyys+++oso/...`````..
```````..:sysyhhhhhhyhddddddddddddhhhhhhhhdhhhhhhys+/+oyhhdhysshhdhhyo+yhhyhhdhsosoooooso/..``````..
```````.:/+syyyyhhhdyhhddhdssshhysyyyhyyhhddhhhdhys/:/ohddmdddhhyyhddhoydyddddhdyysooosso/..``````..
`````.::-/osyyhhhhhddhhdhdhhddhyhhhddddddddmmmdddhso///symmmdmmdhysshhsodyymdddddyyyyyysy/..``````..
`````-`./ooyyhhhhhdhhhdhddsshdydddddddddmmdmmmmhshs+:`-/ohddddddhyso+++/dsommmmddhddhhys+/..``````..
`````.`-/+oohhyhhdhhddddddhddhshddhhdhddddddmddsshy+:..--osyyyssso+:..-/s+smmmmdhddhhhs/:..```````..
``````.-/++syyhhhhdddddddddhyysosysosyyhhhdddhs+ohso:..---ooo+/::--..-:o++oddddhddddhs:...````````..
```````.-:/syhhdhddddddddhoooossosssssoooossssyydyo+/-..---so/////::/+so/:-+dddhdddho-..``````````..
``````````:ssyyhddddddddds++oooss+o+++++oosyyyyhhsooo+/-::::oo+++osssso/---:yhddhdo/-..```````````..
``````````-osysyhdhhhhddds+++++ooooo+++oosyyhhyysssyhyyyyys/:sooo++oss+:---:ohddyy/-..````````````..
``````````./+ssyhhdddyhdds+++++++ooosssssssyhhyshddddmmmmmdho/ossooss+/::-::+yhhs+:..`````````````..
```````````-/ossshddyydddyo++++++ooosossssyhhhhydmdddmmmmmmh+--/ossso//::::/+hhho+-..`````````````..
````````````.-://yddyhddhhs++ooooooosssssyyyyhhhhyydmmmmdhy/...-:+o+//::////+yyys+-..`````````````..
``````````````.--+hdyhhhhhyoooooooooossssyyyyyyyyhhhhdmdoo/-....--:::://++++oysos+-.``````````````..
````````````````-/sdyhddhdhsoooooooosssssssssyyyyyhhyssso++/:---:::::::/++ooss++s/..``````````````..
````````````````.-/shyhhhhhysooosooosooooosyyyyyyyhddhhhhdhy++ossoo+////+ooyys+/:-.```````````````..
`````````````````./oyhssyhhyyssssooooooosyhhhyyhdddddddhhyhhhhhdddhso+//+osyy+:-..````````````````..
`````````````````.:+ooooshdhhysssoooo+ooyhddddhhhhhhhhysoo++//osyhhyso++osyhy/-..`````````````````..
``````````````````.:+o+oshhdhyyssssoooosyhddhhyhhhddddddhhyso+/+oossssooshhhs/-..`````````````````..
````````````````````.--/oyhddhyyyssssoosyhhhhhhhhhdddddhhhyssso+ooosssssyhddo:-..`````````````````..
`````````````````````..-+shhhhhyyyyssoosyhyhhyhhhhhyso+///:::///+oossyyyhddy/-...`````````````````..
``````````````````````..-:ohhdhhhyyyssssyyyhyyyyso+//:::---..--::/oosyyhddh+-...``````````````````..
```````````````````````...:+yhhhhhhhyyyyyhyyyyssoo++++++++////+++osssyhddho:-...``````````````````..
`````````````````````````..-/syhhhhddhhhhhyhyyysssyssssssyysssyyshhdddddy+:-...````````````````.....
`````````````````````````...-:+shdddddddddddhhhhhhhhhhhddddddddddmmmmddy/:-....````````````````....-
`````````````````````````....--:oyhddddmmddddddddddddddddddddmmmmmmmmdh+--.......```````...........-
``````````````````````````....:/+ossyddmmmmmmmmmmmmmdmmmmmmmmmmmmmmmmhy:-..........................-
````````````````````````.....:oyhyssssyhhddmmmmmmmmmmmmmmmmmmmmmmmmmdyo--..........................-
````````````````````````....-+oshdmdhhhyyyyhhhhhdddmmmmmmmmmmmmmmmmdyooo+/--.......................-
`````````````````...`......:+oosyhddmmmmmdddhhyyyhddmmmmmmmmmmmmmmmhsosddys/:-.....................-
`````````````.............:ooooossyhdmmmmmmmmmmmdddmmmmmmmmmmmmmmmdyooymmmdhs+:-...................-
`````````````............-++oooosossyhdmmmmmmmmmmmmmmmmmmmmmmmmmmmhsoohmmmmdhy+/:-.................-
````````````............-/++oooooosssyhhdmmmmmmmmmmmmmmmmmmmmmmmmhsoooshmmmmdyy+/:-...............--
...``.`................/oo+++oooossssyhdmmmmmmmmmmmmmmmmmmmmmmmdhsoo+ohhhhdmhyshyso:-.............--
................-+oso+/osooo+oooossyhmmmmmmmmmmmmmmmmmmmmmmmmdmhsooooodmmy+mhyodmmmh---...........--
.............-:+yhhhddhhysooo++ooshmmmmmmNmmddmmmmmmmmmmmmmmmmdysoossoymmo/ddmsdmmmms:---.........--
..---:/+ooooosyyhhhhhdmmyso+oooosymmmmmNNNmdmmmmmmmmmmmmmmmmmmhysssssosdo+shmmddmmmmh++//:::::------
.:osyddhdddhhyhhhdddddmmysooooossdmmmmmmmmmmmmmmmmmmmmmmmmmmmdhyyssysso/oshhmmmhymmmhooo+++++++o++/-
-+yhhhddddddddhhhhddmmmmhysosssyhmmmmmmmmmmmmmmmmmmmmmmdmmdhysyyyyhhs++ooyhyddddydmmhooo++++//+++o+:
-/ooossssssssssssssssssssssooooossssssssssssssssssssssysssssoo+++++++oooosooo+++osyso++++++++//////:
"""
