id = "olmec_mask"  # Gleaned from https://collections.artsmia.org/art/62148/mask-olmec
name = "Mask, Olmec c. 900-300 BCE"
ascii_data = """
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddhhhhhhddddddddddddddddhhhhdddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddddddhhdddddddddddddddddd
ddddddddhhdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddd
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddd
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyssoo+++++++++++++++++o++++++osssyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhyssooo++++o+++++++ooooo+oo++o+oo+++++++++++oosyyhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhyso+++++o+++ooooo+ooooosoooooosoooooo+oo++oo++++++ooyhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhoo+ooooooooooooo+o++oossssssssossssoooooooooooo+++++osyhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhy+++oooosooooooooooooosssssssssssssososoooooooooo++++osohhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhys+ooosssssssoooooooossssssssssssssssssssssssssssoooooosoyhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhyhhyyyyyyyysossssssssssssooooooosssssssssyyssyyyyysyysssssssoooosssyyyhhhyhhhhhhhhhhhhhhh
hhhhhhyyyyyyyyyyyyyyyysssssyyysyyyyyyyysyssssssyssssyyssyyyyyyyyyyyyyyssssoosoyyyyyyyyyyhhhhhhhhhhhh
yyyyyyyyyyyyyyyyyyyyyyyssssosooosssssssyyyyyysyyyyysyyyhyyyyyyyyyyyyyyssssssssyyyyyyyyyyyyyyyyyyyyhh
yyyyyyyyyyyyyyyyyyyyyysssssssooooooooosyyyyyyyyyyyyyyyyyyhyhyyysssssssooossssssyyyyyyyyyyyyyyyyyyyyy
yyyyyyyyyyyyyyyyyyyysossssysssssossososssyyyyyyyyyyyyyyyhhhysssoossoosssssssyysyyyyyyyyyyyyyyyyyyyyy
yyyyyyyyyyyyyyyyyyyysosyysyyssyyssssssooosyyyyyyyssyyyyhhhyyysssssssssyssyysyyssyyyyyyyyyyyyyyyyyyyy
yyyyyyyyyyyyyyyyyyyyssssysyyyyyhhhhhhhyssssyyyyso++osyyhhyyyyyhhhhhhyyyyyyyyyyssyyyyyyyyyyyyyyyyyyyy
yyyyyyyyyyyyyyyyyyyysossssssyyhdmNNNNNmhysssyysso+/+osyhyyyyhmNNNNNNdhhhhyyyyysosyyyyyyyyyyyyyyyyyyy
yyyyyyyyyyyyyyyyyyyysossooo+osyhdmmmmdhssssssyso++/+ossyyyyyyhdmmmmmdhhhysssossoyyyyyyyyyyyyyyyyyyyy
yyyyyyyyyyyyyyyyyyyyssssooo+++oossssssssyssssso+++/++ossyyyyyysssssooooo+oooossssyyyyyyyyyyyyyyyyyyy
yyyyyyyyyyyyysssssssyssysooosssyyyyyyyyyyssooo++++/++oooosyyyyyyyyhyyyyysooossssyyyysyyyyyyyyyyyyyyy
yyyyyyssssssssssssssysssssoooosssyyyyyyssoo++//++++++ooo+oosssyyyyyyyyyyyooossssyssssssssssyyyyyyyyy
ssssssssssssssssssssysssssssssosssssoooooo++///++oooo+++++oooossssssyyssssssssssyssssssssssssssssyyy
ssssssssssssssssssssyssssssssoooo+++++oo+++////+syyyso+++++ooooooooooosossssssssysssssssssssssssssss
ssssssssssssssssssssysosyssssooooo+++++++++///+oshhhyo//+++ooosoooossssossssssosysssssssssssssssssss
ssssssssssssssssssssssossyyssssoso+++++/+///++osyhdhyso+++++oooooooosooossssssssysssssssssssssssssss
sssssssssssssssssssssyosyyyssssooo++++++/+/ssssyhhdhhyyyys+++++ooooosossssssyyoyssssssssssssssssssss
sssssssssssssssssssssyssssyyssssoooo+++++/:osyyyyhyyyyyyyy+//+oooosssssssssyyysyssssssssssssssssssss
sssssssssssssssssoooosyhssyyssssoooooo+////+++osyhhhyssoo++///++oooossssssyyyhysooosssssssssssssssss
ssssssssooooooooooooooshssyyssssoooooo+/+/+oossssysysssoo++//+/+oosssssssyyyyysoooooooooooosssssssss
ooooooooooooooooooooooooosyyysssoooo+++++sssssyyyyyyyyyysssso+++oosssssssyyyyooooooooooooooooooooooo
ooooooooooooooooooooooooosyssssssoooo+oosyyyysyyyyyyyyyyyysyyso++oooossssyyysooooooooooooooooooooooo
ooooooooooooooooooooooooossysysssooooosyyyyssyyyyhyhhyyyyyyyyysooosssssyyyyyoooooooooooooooooooooooo
oooooooooooooooooooooooooosyssssssoosssyyyyyyyyysssyyyyyyyyyyyyssssssssyyyyso+++oooooooooooooooooooo
oooooooo++++++++++++++++++ssssssssoosssyhhysooo+++++oooosyhhhyyysssssssyyyyo+++++++++++++++++++++ooo
++++++++++++++++++++++++++osssssssoooooooooooossssysssssoooyhysyssssssssyys+++++++++++++++++++++++++
+++++++++++++++++++++++++++oysssssosooosssyyyyyhhyhhhhhhyyyyssssssssysyyys+////+++++++++++++++++++++
+++/////////////////////////sssssssssssssssyyyyyysyyyyyyyyyyyssssssyyyyyyo//////////////////////////
/////////////////////////////ssssssssssssssyyyyyyyyyyyyyyyyssssssssyyyyyo///////////////////////////
/////::::::::::::::::::::::::/sysssssssssssssssssyyyssyyyssssssysssyyyyo::::::::::::::::::::::::::::
:::::::::::::::::::::::::::::::ossssssoossoosssyyyyyysssssssssssssyyys/:::::::::::::::::::::::::::::
:::::::::-----------------------:osssssossossyyyhhhyyyysssssssssyyso/---------------------::::::::::
----------------------------------:/ossssssyyyhhhhhhyyyyyyyyyysso/:---------------------------------
--------------------------------------:/+ssyyhhhhhhhhhhhyyyso/:-------------------------------------
-------------.............................--://++hdddo//:--.............................------------
.................................................dmmm/..............................................
.................................................hmmm/..............................................
.................................................hmmm/..............................................
.................................................hmmm+..............................................
"""